// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://adgjmkkiaeffonyzsyjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZ2pta2tpYWVmZm9ueXpzeWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1ODgwMjYsImV4cCI6MjA4NzE2NDAyNn0.pZ3eBbW9vrLx7sieP6jJp2al7Ty2yTV9DCBWaqazNNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
