// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://adgjmkkiaeffonyzsyjw.supabase.co";
export const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZ2pta2tpYWVmZm9ueXpzeWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1ODgwMjYsImV4cCI6MjA4NzE2NDAyNn0.pZ3eBbW9vrLx7sieP6jJp2al7Ty2yTV9DCBWaqazNNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * Direct edge function invocation that bypasses supabase.functions.invoke()
 * to avoid 401 errors caused by JWT verification config mismatch.
 * Uses the user's session token when available, falls back to anon key.
 */
export async function invokeEdgeFunction<T = any>(
  functionName: string,
  body?: Record<string, unknown>,
): Promise<{ data: T | null; error: Error | null }> {
  try {
    const session = (await supabase.auth.getSession()).data.session;
    const res = await fetch(`${SUPABASE_URL}/functions/v1/${functionName}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "apikey": SUPABASE_ANON_KEY,
        "Authorization": `Bearer ${session?.access_token || SUPABASE_ANON_KEY}`,
      },
      body: body ? JSON.stringify(body) : undefined,
    });
    if (!res.ok) {
      const text = await res.text().catch(() => "");
      return { data: null, error: new Error(`HTTP ${res.status}: ${text}`) };
    }
    const data = await res.json();
    return { data, error: null };
  } catch (err: any) {
    return { data: null, error: err };
  }
}